### ISSUE TITLE
Merge In Old Company Guidelines

### ISSUE THREAD

**Issue by JEG2** [NoRedInk/ruby-style-guide#5]
https://github.com/NoRedInk/wiki/blob/master/eeps/Ruby-Best-Practices.md

**Comment by michaelglass** [comment]
can we close this?

**Comment by JEG2** [comment]
It still isn't merged.

This is needed to do so:  https://noredink.slack.com/files/glass/F1N5KL6KF/style-guide.tar.xz

**Comment by michaelglass** [comment]
the only uncovered rule from the style guide there is: "Use expanded regular expression syntax"

**Comment by michaelglass** [comment]
also: fwiw, we've never really followed that rule and I'm a little ambivalent about really codifying it.

The rest of the stye guide covered `.hamlc` (e.g. haml compiled to js) files that we don't use anymore and coffeescript, which we mostly don't use anymore.

**Comment by rtfeldman** [comment]
> we've never really followed that rule and I'm a little ambivalent about really codifying it.

Closing based on this comment from over a year ago; seems like codifying this would not be time well spent.

If anyone disagrees, feel free to reopen!
