### ISSUE TITLE
How will this guide be maintained?

### ISSUE THREAD

**Issue by ento** [NoRedInk/ruby-style-guide#7]
Specifically, will we be rebasing on / merging upstream regularly? Example of a such process:
1. [Maintainer] checks for drift regularly
2. [Maintainer] merges using their best intentions
3. [Maintainer] asks team for opinions

**Comment by JEG2** [comment]
I'm not sure if that's really needed to be honest.

The guides kind of have two different purposes.  The upstream repository is trying to satisfy the overall community.  The primary purpose of our guide is just to give us a common framework.

So, I think it would be acceptable for us to say that we'll change our guide as we decide we need to.  It can have it's own independent life from here.  (Obviously, this had the advantage of less work on our end.)

That said, keeping in sync could expose us to new or changing ideas.  It probably is a decent idea to check changes on the other end periodically just to see what's happening there I guess.

I'm comfortable with either approach.

**Comment by ento** [comment]
I'm fine with either too, as long as we make a conscious decision about it.

I think a good time to check for what's happening in the external world would be
- New syntax gets introduced to Ruby, which is when we upgrade Ruby
- We adopt a new library that comes with a sophisticated DSL

Both will throw us in a situation where we face a piece of code we don't know how to format, so it'll serve as a trigger. So: I'd be happy with the "change our guide as we decide we need to" approach.

**Comment by JEG2** [comment]
:heart:
